package {{.PackageName}}

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "{{.BaseName}}.h"
import "C"
import (
	{{if not .Classes}}_ {{end}}"runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.{{.SanitizedBaseName}}_module_entry))
}

{{- range .Functions}}
//export go_{{.Name}}
func go_{{.Name}}({{extractGoFunctionSignatureParams .GoFunction}}) {{extractGoFunctionSignatureReturn .GoFunction}} {
	{{if not (isVoid .ReturnType)}}return {{end}}{{extractGoFunctionName .GoFunction}}({{extractGoFunctionCallParams .GoFunction}})
}

{{- end}}
{{- if .Classes}}
//export registerGoObject
func registerGoObject(obj interface{}) C.uintptr_t {
	handle := cgo.NewHandle(obj)
	return C.uintptr_t(handle)
}

//export getGoObject
func getGoObject(handle C.uintptr_t) interface{} {
	h := cgo.Handle(handle)
	return h.Value()
}

//export removeGoObject
func removeGoObject(handle C.uintptr_t) {
	h := cgo.Handle(handle)
	h.Delete()
}

{{- end}}
{{- range $class := .Classes}}
//export create_{{.GoStruct}}_object
func create_{{.GoStruct}}_object() C.uintptr_t {
	obj := &{{.GoStruct}}{}
	return registerGoObject(obj)
}

{{- range .Methods}}
//export {{.ClassName}}_{{.Name}}_wrapper
func {{.ClassName}}_{{.Name}}_wrapper(handle C.uintptr_t{{range .Params}}, {{.Name}} {{goParamType .PhpType .IsNullable}}{{end}}){{if not (isVoid .ReturnType)}} {{goReturnType .ReturnType}}{{end}} {
	obj := getGoObject(handle)
	if obj == nil {
{{- if isVoid .ReturnType}}
		return
{{- else}}
		var zero {{goReturnType .ReturnType}}
		return zero
{{- end}}
	}
	structObj := obj.(*{{$class.GoStruct}})
	{{if not (isVoid .ReturnType)}}return {{end}}structObj.{{extractGoFunctionName .GoFunction}}({{range $i, $param := .Params}}{{if $i}}, {{end}}{{$param.Name}}{{end}})
}
{{end}}
{{- end}}
